# NumPy-Arrays vs. Python-Listen
## Aufgabe 3 Übungsblatt 2

In [1]:
#!pip install numpy

import numpy as np
import time

In [2]:
size = 1000000

x = np.arange(size) # numpy-array zwischen 0-size mit Schrittgröße 1
y = list(range(size)) # Python Liste mit Elementen 0-size mit Schrittgröße 1

print(x[:10])
print(y[:10])

print(sum(x==y)) # Prüfen ob alle Elemente gleich sind



[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1000000


In [3]:
# Numpy Array: Quadrieren der Elemente 
start = time.time()
x_sq = np.square(x)
end = time.time()
print('Dauer des Quadrierens: ', end - start)
print(x_sq[:10])

Dauer des Quadrierens:  0.00222015380859375
[ 0  1  4  9 16 25 36 49 64 81]


In [4]:
# Power
a = np.arange(10)
print('a = ', a)
print('a^2 = ', a^2) # Bitweises XOR
x1 = 3 # Binär '11'
x2 = 2 # Binär '10'
print('x1^x2 = ', x1^x2) # Bitweises XOR: 1 XOR 1 = 0, 1 XOR 0 = 1, Ergebnis ist '01' in dezimalschreibeweise 1

print('square(a) = ', np.square(a))
print('a*a = ', a*a)
print('a**2 = ', a**2)



a =  [0 1 2 3 4 5 6 7 8 9]
a^2 =  [ 2  3  0  1  6  7  4  5 10 11]
x1^x2 =  1
square(a) =  [ 0  1  4  9 16 25 36 49 64 81]
a*a =  [ 0  1  4  9 16 25 36 49 64 81]
a**2 =  [ 0  1  4  9 16 25 36 49 64 81]


In [5]:
# List - Loop - Quadrieren der Elemente
y_sq = y
start = time.time()
for i in range(len(y)):
    y_sq[i] = y[i]**2
end = time.time()
print(end - start)

print(y_sq[:10])
print(sum(y_sq == x_sq))

0.2456209659576416
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
1000000


In [6]:
# List - Loop - List Comprehensions
start = time.time()
y_squared = [i ** 2 for i in y]
end = time.time()
print(end - start)

print(y_sq[:10])
print(sum(y_sq == x_sq))

0.22321701049804688
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
1000000


## Aufgabe 4 Übungsblatt 2

In [7]:
a = np.arange(100)
a = a.reshape(10,10)+1
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [8]:
print(a[[0,4,9],])
print(a[[0,4,-1],])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [9]:
print(a[1::2,[2,6]])


[[13 17]
 [33 37]
 [53 57]
 [73 77]
 [93 97]]


In [10]:
print(a[0:3,0:3])

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [11]:
a[[1,3],] = -a[[1,3],]
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [-11 -12 -13 -14 -15 -16 -17 -18 -19 -20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [-31 -32 -33 -34 -35 -36 -37 -38 -39 -40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [12]:
a[a<25] = 0
print(a)

[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  25  26  27  28  29  30]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
