## The NumPy Array
Basierend auf Kyran Dale
https://github.com/Kyrand/dataviz-with-python-and-js-ed-2.git

# Das ist eine Überschrift 1
## Das ist eine Überschrift 2

**Fett** oder normal geschriebener Text
- Aufzählungspunkt 1
- Aufzählungspunkt 2

1. Nummerierte Liste Punkt 1
2. Nummerierte Liste Punkt 2


In [46]:
import numpy as np

In [47]:
print('Hallo Welt')

Hallo Welt


In [51]:
a = np.array([1, 2, 3]) # Horizontaler Vektor
a1 = np.array([[1], [2], [3]]) # Vertikaler Vektor

b = np.array([1,2,3,'text'])

print('a = ', a)
print('a+a = ', a + a)
print('a1 = ', a1)
print('b = ',b)


a =  [1 2 3]
a+a =  [2 4 6]
a1 =  [[1]
 [2]
 [3]]
b =  ['1' '2' '3' 'text']


In [52]:
def print_array_details(a):
    print('Dimensions: %d, shape: %s, dtype: %s'%(a.ndim, a.shape, a.dtype))

In [53]:
print_array_details(a)
print_array_details(a1)
print_array_details(b)

Dimensions: 1, shape: (3,), dtype: int64
Dimensions: 2, shape: (3, 1), dtype: int64
Dimensions: 1, shape: (4,), dtype: <U21


In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Alternativ
a1 = np.array(list(range(1,10,1))) # range erzeugt Zahlen von 1 bis 10 mit Abstand 1
print('a1 = ', a1)

a1 =  [1 2 3 4 5 6 7 8 9]


In [6]:
print_array_details(a)

Dimensions: 1, shape: (8,), dtype: int64


In [7]:
a = a.reshape([2, 4])
print('a =', a)
print_array_details(a)

a = [[1 2 3 4]
 [5 6 7 8]]
Dimensions: 2, shape: (2, 4), dtype: int64


In [8]:
a = a.reshape([2, 2, 2])
print('a =', a)

a = [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print_array_details(a)

Dimensions: 3, shape: (2, 2, 2), dtype: int64


In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x.shape

(2, 3)

In [11]:
x.shape = (6,)
x

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [12]:
x = x.astype('int64')
x.dtype

dtype('int64')

## Creating Arrays

In [13]:
a = np.zeros([2,3])
print("a = ", a)
print(a.dtype)

a =  [[0. 0. 0.]
 [0. 0. 0.]]
float64


In [14]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
empty_array = np.empty((2,3))
print("empty_array = ", empty_array) # Die Werte des Arrays sind nicht-deterministisch
print(empty_array.dtype)

empty_array =  [[1. 1. 1.]
 [1. 1. 1.]]
float64


In [16]:
np.random.random((2,3)) # random: Random Sampling in numpy; random: Werte zwischen 0<=x<1

array([[0.28256321, 0.48164097, 0.60805239],
       [0.58924103, 0.03214292, 0.25812   ]])

In [17]:
np.random.normal(0,1, (2,3)) # normal: Normalverteilung mit Mittelwert 0, Standardabweichung 1 und Shape (2,3)

array([[ 1.88701447,  0.69063513,  0.06020494],
       [-0.77279452, -0.15457942, -1.27727871]])

In [18]:
a = np.linspace(2, 10, 5) # 5 numbers in range 2-10
print("a = ", a)
print(a.dtype)

a =  [ 2.  4.  6.  8. 10.]
float64


In [19]:
a = np.arange(2, 10, 2)
print("a = ", a)
print(a.dtype)

b = np.arange(2, 10, 2.)
print("b = ", b)
print(b.dtype)

a =  [2 4 6 8]
int64
b =  [2. 4. 6. 8.]
float64


## Aufgabe

In [2]:
import numpy as np # falls noch nicht importiert

arr = np.arange(10)
print("Array:", arr)
print("Dimension:", arr.ndim)
print("Shape:", arr.shape)
print("Datentyp:", arr.dtype)

Array: [0 1 2 3 4 5 6 7 8 9]
Dimension: 1
Shape: (10,)
Datentyp: int64


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Addition:", a + b)
print("Subtraktion:", a - b)
print("Multiplikation:", a * b)
print("Mittelwert a:", np.mean(a))
print("Mittelwert b:", np.mean(b))

a1 = a
a1[a1<np.mean(a1)] = 0
print("Alle Elemente <mean(a)=0: ", a1)

b1 = b
b1[b1<np.mean(b1)] = 0
print("Alle Elemente <mean(b)=0: ", b1)

Addition: [11 22 33 44 55]
Subtraktion: [ -9 -18 -27 -36 -45]
Multiplikation: [ 10  40  90 160 250]
Mittelwert a: 3.0
Mittelwert b: 30.0
Alle Elemente <mean(a)=0:  [0 0 3 4 5]
Alle Elemente <mean(b)=0:  [ 0  0 30 40 50]


## Array Indexing and Slicing

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
print("a[2] = ", a[2])


a[2] =  3


In [21]:
a[3:5]

array([4, 5])

In [22]:
# every second item from 0-4 set to 0
a[:4:2] = 0
a

array([0, 2, 0, 4, 5, 6])

In [23]:
a[::-1]

array([6, 5, 4, 0, 2, 0])

In [24]:
a = np.arange(16)
a = a.reshape(2,2,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [25]:
print(a[0])
print(np.array_equal(a[0,:,:], a[0]))
print(a[0,0,:])

[[0 1 2 3]
 [4 5 6 7]]
True
[0 1 2 3]


In [26]:
print(a[0,0,::2])

[0 2]


# Fancy Indexing

In [27]:
a = np.arange(10)
print('a = ', a)
i = np.array([2, 1, 8, 4]) # array aus indizes
a[i] = 99
print('a = ', a)

a =  [0 1 2 3 4 5 6 7 8 9]
a =  [ 0 99 99  3 99  5  6  7 99  9]


In [28]:
a[i] -= 10
print('a = ', a)

a =  [ 0 89 89  3 89  5  6  7 89  9]


In [29]:
# Auswahl Werte mit geradem Index ab 0
print('a = ', a[::2])

a =  [ 0 89 89  6 89]


In [30]:
# Boolsche Indexierung
print('a = ', a<10)

a =  [ True False False  True False  True  True  True False  True]


## A Few Basic Operations

In [31]:
a = np.arange(6)
a = a.reshape(2,3)
print('a = ', a)
print('a+2 = ', a+2)
print('a-2 = ', a-2)
print('a/2 = ', a/2.0)

a =  [[0 1 2]
 [3 4 5]]
a+2 =  [[2 3 4]
 [5 6 7]]
a-2 =  [[-2 -1  0]
 [ 1  2  3]]
a/2 =  [[0.  0.5 1. ]
 [1.5 2.  2.5]]


In [32]:
a = np.array([45, 65, 76, 32, 99, 22])
a < 50

array([ True, False, False,  True, False,  True])

In [33]:
# Some array methods
a = np.arange(8).reshape((2,4))
print('a = ', a)

# Minimum
print('a.min(axis=1) = ', a.min(axis=1))
# Summe
print('a.sum(axis=0) = ', a.sum(axis=0))
# Mittelwert
print('a.mean(axis=1) = ', a.mean(axis=1))
# Standardabweichung
print('a.std(axis=1) = ', a.std(axis=1))

a =  [[0 1 2 3]
 [4 5 6 7]]
a.min(axis=1) =  [0 4]
a.sum(axis=0) =  [ 4  6  8 10]
a.mean(axis=1) =  [1.5 5.5]
a.std(axis=1) =  [1.11803399 1.11803399]


In [34]:
# Trigonometric functions
pi = np.pi
a = np.array([pi, pi/2, pi/4, pi/6])
np.degrees(a) # radians to degrees

array([180.,  90.,  45.,  30.])

In [35]:
sin_a = np.sin(a)
sin_a

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 5.00000000e-01])

In [38]:
np.cumsum(a, axis=1) # cumulative sum along second axis

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22]])

In [39]:
np.cumsum(a) # without axis argument, array is flattened

array([ 0,  1,  3,  6, 10, 15, 21, 28])